// swift-tools-version:5.9
// Copyright 2026 tauri-plugin-ad2mob contributors
// SPDX-License-Identifier: Apache-2.0
// SPDX-License-Identifier: MIT

import PackageDescription

let package = Package(
  name: "tauri-plugin-ad2mob",
  platforms: [
    .iOS(.v13),
  ],
  products: [
    // Products define the executables and libraries a package produces, and make them visible to other packages.
    .library(
      name: "tauri-plugin-ad2mob",
      type: .static,
      targets: ["tauri-plugin-ad2mob"])
  ],
  dependencies: [
    // Tauri iOS plugin API, generated by the Tauri CLI at `gen/apple/.tauri/tauri-api`.
    .package(name: "Tauri", path: "../.tauri/tauri-api"),
    // Google Mobile Ads SDK (13.x): banner, interstitial and rewarded ads.
    .package(
      url: "https://github.com/googleads/swift-package-manager-google-mobile-ads.git",
      from: "13.0.0"),
    // Google User Messaging Platform (3.x): UMP consent flow.
    .package(
      url: "https://github.com/googleads/swift-package-manager-google-user-messaging-platform.git",
      from: "3.0.0")
  ],
  targets: [
    // Targets are the basic building blocks of a package. A target can define a module or a test suite.
    // Targets can depend on other targets in this package, and on products in packages this package depends on.
    .target(
      name: "tauri-plugin-ad2mob",
      dependencies: [
        .byName(name: "Tauri"),
        .byName(name: "GoogleMobileAds"),
        .byName(name: "GoogleUserMessagingPlatform")
      ],
      path: "Sources"),
    .testTarget(
      name: "tauri-plugin-ad2mob-tests",
      dependencies: [
        .byName(name: "tauri-plugin-ad2mob")
      ],
      path: "Tests/PluginTests")
  ]
)
